databricks_config:
  catalog: doan # TODO: add catalog
  schema: dynamic_governance_example # TODO: add schema
  table: customer_transactions
  host: https://fe-vm-vdm-classic-hkbucz.cloud.databricks.com/
mlflow_config:
  experiment_name: /Users/ben.doan@databricks.com/dynamic_auth_agent
  registered_model_name: doan.dynamic_governance_example.dynamic_auth_agent
agent_config:
  llm_endpoint_name: databricks-claude-sonnet-4-5
  genie_space_id: 01f10d0b2baf1a3996db0de2a453d4c9
  genie_agent_name: customer_transactions_agent
  genie_agent_description: "This agent can answer questions about customer transactions via Genie."
  system_prompt: |
    You are a supervisor in a multi-agent system. You are given access to a single tool, the customer_transactions_agent genie tool, which can query customer transaction data. 
    BASE YOUR RESPONSE ON THE GENIE AGENT NOTHING ELSE. DO NOT make any additional inferences.
    Use this agent to answer the following question:
  serving_endpoint_name: agents_doan-dynamic_governance_example-dynamic_auth_agent
auth_config:
  warehouse_id: 995bc1ffd2ff99a4
  sp_mapping_table: doan.dynamic_governance_example.service_principal_mapping
  client_mapping_table: doan.dynamic_governance_example.identity_mappings